---
- hosts: webwork-dev
  user: vagrant
  vars:
    webwork_version: "WeBWorK-2.7"
    pg_version: "PG-2.7"
  tasks:
    - name: Install Webwork dependencies
      apt:
        name: "{{ item }}"
        state: "installed"
      with_items:
        - apache2
        - apache2-mpm-prefork
        - dvipng
        - gcc
        - git
        - libapache2-request-perl
        - libdatetime-perl
        - libdbd-mysql-perl
        - libemail-address-perl
        - libexception-class-perl
        - libextutils-xsbuilder-perl
        - libfile-find-rule-perl
        - libgd-gd2-perl
        - libhtml-scrubber-perl
        - libjson-perl
        - liblocale-maketext-lexicon-perl
        - libmail-sender-perl
        - libmime-perl
        - libnet-ip-perl
        - libnet-ldap-perl
        - libnet-oauth-perl
        - libossp-uuid-perl
        - libpadwalker-perl
        - libphp-serialization-perl
        - libsoap-lite-perl
        - libsql-abstract-perl
        - libstring-shellquote-perl
        - libtext-csv-perl
        - libtimedate-perl
        - libuuid-tiny-perl
        - libxml-parser-perl
        - libxml-writer-perl
        - make
        - mysql-server
        - netpbm
        - openssh-server
        - preview-latex-style
        - texlive
        - unzip
        - cpanminus
    - name: Install perl dependencies from CPAN
      cpanm:
        name: "{{ item }}"
      with_items:
        - XML::Parser::EasyTree
        - Iterator
        - Iterator::Util
        - Pod::WSDL
    - name: Check out webwork from github
      git:
        repo: "https://github.com/openwebwork/webwork2"
        version: "{{ webwork_version }}"
        dest: /opt/webwork/webwork2
    - name: Check out pg from github
      git:
        repo: "https://github.com/openwebwork/pg"
        version: "{{ pg_version }}"
        dest: /opt/webwork/pg
    - name: Checkout OPL from github
      git:
        repo: "https://github.com/openwebwork/webwork-open-problem-library"
        dest: /opt/webwork/libraries/webwork-open-problem-library
    - name: Create wwdata group for Webwork files
      group:
        name: wwdata
        state: present
    - name: Create courses directory
      file:
        path: /opt/webwork/courses
        state: directory
        owner: vagrant
        group: wwdata
    - name: Apache2 configuration
      command: a2enmod apreq
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
    - name: Add vagrant user to wwdata group
      user:
        name: vagrant
        append: yes
        groups: wwdata
    - name: Add www-data user to wwdata group
      user:
        name: www-data
        append: yes
        groups: wwdata
    - name: Set ownership on Webwork files
      file:
        path: /opt/webwork
        state: directory
        recurse: yes
        owner: vagrant
        group: wwdata
    - name: Set permissions on Webwork files
      command: "chmod -R u+rwX,go+rX /opt/webwork"
    - name: Set writable directories
      command: "chmod -R g+w DATA ../courses htdocs/tmp logs tmp"
      args:
        chdir: /opt/webwork/webwork2
    - name: Set sticky bits
      command: "find DATA/ ../courses/ htdocs/tmp logs/ tmp/ -type d -a -exec chmod g+s {} \\;"
      args:
        chdir: /opt/webwork/webwork2
    # - name: Check dependencies
    #   command: /opt/webwork/webwork2/bin/check_modules.pl apache2
    - name: Copy Webwork site.conf
      copy:
        src: conf/site.conf
        dest: /opt/webwork/webwork2/conf/
    - name: Copy Webwork conf files
      copy:
        src: conf/localOverrides.conf
        dest: /opt/webwork/webwork2/conf/
    - name: Copy webwork apache configuration
      command: "cp webwork.apache2-config.dist webwork.apache2-config"
      args:
        chdir: /opt/webwork/webwork2/conf
        creates: /opt/webwork/webwork2/conf/webwork.apache2-config
    - name: Symlink apache2 configuration
      file:
        src: /opt/webwork/webwork2/conf/webwork.apache2-config
        state: link
        path: /etc/apache2/conf.d/webwork.apache2-config
    - name: Reload Apache2
      service:
        name: apache2
        state: reloaded
